### ISSUE TITLE
Cargo errors out on "cargo check"

### ISSUE THREAD

**Issue by RalfJung** [rsolomo/cargo-check#10] opened 2016-04-28 14:47 UTC
After installing cargo-check, when I try to use it, I get the following error:
```
$ PATH=$HOME/r/.cargo/bin:$PATH cargo check
error: extra arguments to `rustc` can only be passed to one target, consider filtering
the package by passing e.g. `--lib` or `--bin NAME` to specify a single target
error: third party subcommand `cargo-check` exited unsuccessfully

To learn more, run the command again with --verbose.
```
This is with
```
$ rustc --version
rustc 1.9.0-beta.1 (37a2869af 2016-04-12)
```
but I already saw this with the 1.8 betas.

**Comment by shepmaster** [comment] 2016-06-28 21:17
Duplicate of #4

**Comment by rsolomo** [comment] 2016-06-28 21:21
closing due to being a duplicate of #4

**Closed by rsolomo** 2016-06-28 21:21 UTC
